-- Creating table Departments
CREATE TABLE DEPARTMENTS(
DEPT_ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

-- Inserting values into it.
INSERT INTO DEPARTMENTS
VALUES
(501,"CUTTING"),
(502,"STITCHING"),
(503,"FINISHING"),
(504,"PACKAGING"),
(505,"QUALITY CHECK");