-- Creating Table Products that will have the list of all the products available at the RANCHO Shirt manufacturing factory.
CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY,
NAME VARCHAR(70),
CATEGORY VARCHAR(50),
SICE VARCHAR(5),
COLOUR VARCHAR(20),
PRICE INT
);

-- Inserting values into the table Products
INSERT INTO PRODUCTS
VALUES
(101,"CLASSIC FORMAL SHIRT","FORMAL WEAR","M","WHITE",899),
(102,"CASUAL CHECKED SHIRT","CASUAL WEAR","L","BLUE",749),
(103,"SLIM FIT DENIM SHIRT","CASUAL WEAR","M","BLACK",999),
(104,"LINEN SUMMER SHIRT","SUMMER WEAR","S","BEIGE",1099),
(105,"OFFICE COTTON SHIRT","FORMAL WEAR","L","SKY BLUE",849),
(106,"PARTY WEAR SHIRT","PARTY WEAR","XL","MAROON",1299),
(107,"PRINTED COTTON SHIRT","CASUAL WEAR","M","GREEN",699),
(108,"PREMIUM SILK SHIRT","PARTY WEAR","L","NAVY",1499),
(109,"STRETCH FIT SHIRT","SPORTS WEAR","M","GREAY",1099),
(110,"DESIGNER COLLAR SHIRT","FASHION LINE","XL","BLACK",1599);